INSERT INTO `clubs_infos` VALUES (0, 1, NULL, 'Réunion éducateurs le mercredi 21/01/2015 à 19h00 au siège château Roy.\r\nMerci de confirmer de votre présence à Denis \r\n\r\n ', NULL);
INSERT INTO `clubs_infos` VALUES (3, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (5, 1, '', 'reunion technique à 18h le 24/11/2014 - futsal le 8/12/2014\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (7, 1, '', 'Pensez à enregistrer vos joueurs sur My Coach', NULL);
INSERT INTO `clubs_infos` VALUES (9, 1, '', 'Un grand merci à tous les Educateurs et bénévoles qui ont contribué à la réussite du tournoi du club.', NULL);
INSERT INTO `clubs_infos` VALUES (10, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (11, 1, '', '03/10  Brassage U8 U9 Stade de Rostit 10 H 00\r\n03/10  Brassage U13 Stade Vanco 13 H 30\r\n03/10  Brassage U10/U11  Stade de la Lauvette 09 H 30\r\nLien tableau et feuille de match : http://cotedazur.fff.fr/cg/6202/www/index.shtml\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (13, 1, '', 'demander aux joueurs de regler les licences', NULL);
INSERT INTO `clubs_infos` VALUES (15, 1, '', 'Merci d\'inscrire vos dates sur le calendrier afin que tous les entraineurs soient au courant.\r\n                                             ', NULL);
INSERT INTO `clubs_infos` VALUES (17, 1, '', 'Amis éducateurs, pour votre effectif, NE CRÉEZ PAS DE JOUEUR, servez vous de la base de données interne du club :\r\nAllez dans \" Effectif \" ,  \" ajouter un joueur \" , \"cliquez sur le lien bleu pour rechercher un joueur du club. \r\nTapez son nom, et choisissez le joueur dont le nom est inscrit de la façon suivante : Eric DURAND (prénom en minuscule, NOM en majuscule). Le joueur doit avoir son numéro de licence déjà connu... Merci, ça évitera les doubles ou triples ! Enfin, supprimez les joueurs créés !', NULL);
INSERT INTO `clubs_infos` VALUES (20, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (31, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (32, 1, '', '\r\n\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (37, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (40, 1, '', ' ', NULL);
INSERT INTO `clubs_infos` VALUES (41, 1, '', 'A la veille de cette nouvelle saison, un rappel pour les spécifiques gardiens Dh seniors le mardi de 20h à 21h, U19dh le mardi 18h30 à 19h30 pour U15 et U17 le vendredi à partir de 17h45 à Sauvaigo et pour l\'école de foot,le mercredi à partir de 13h30 au Val fleuri. Bonne saison , Pascal.\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (44, 1, '', 'Lundi 12 décembre 2011 - Réunion éducateurs - 20 h 00 à la buvette !', NULL);
INSERT INTO `clubs_infos` VALUES (50, 1, '', ' Ca y est une nouvelle saison a commencé. Les seniors ont repris le chemin de Vaugrenier et du terrain. On souhaite beaucoup de réussite à Olivier et Patrice. Allez LA FONTONNE !!!!!!!!!!!!!! Le Président Gilbert RICO', NULL);
INSERT INTO `clubs_infos` VALUES (61, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (70, 1, '', 'A tous les éducateurs, éducatrice, du club de football de Longages\r\nLa présidente espere que MYCOACH sera un bon outil dans vos recherches pour les entraînements\r\na vous de jouer maintenant.....................\r\nBONNE SAISON 2011/2012', NULL);
INSERT INTO `clubs_infos` VALUES (77, 1, '', ' TERRAIN HESPERIDES FERME DU 29 AU 4 NOVEMBRE 2012 - EN RAISON DE LA REFECTION DE LA PELOUSE.\r\nTERRAIN DE REPLI POUR LES SENIORS ET LES U19 (communiqué ultérieurement)', NULL);
INSERT INTO `clubs_infos` VALUES (87, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (98, 1, '', 'LES CALENDRIERS DEVRAIS ÊTRES PRÊTS MERCREDI', NULL);
INSERT INTO `clubs_infos` VALUES (103, 1, '', 'Retour a la competition pour l\'ensemble des équipes du Grand-Quevilly FC ce week-end.....', NULL);
INSERT INTO `clubs_infos` VALUES (110, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (114, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (118, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (119, 1, '', 'Une réunion de formation / information est proposé le mercredi 2 septembre à 20h30 au club house !!! Max sera présent pour vous en parler !!!', NULL);
INSERT INTO `clubs_infos` VALUES (121, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (129, 1, '', '          ', NULL);
INSERT INTO `clubs_infos` VALUES (130, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (132, 1, '', 'soiree du foot le 17 décembre à partir de 20h00', NULL);
INSERT INTO `clubs_infos` VALUES (173, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (197, 1, '', '  F.C.V.L     SALAM ALAYKOUM     F.C.V.L   ', NULL);
INSERT INTO `clubs_infos` VALUES (198, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (201, 1, '', 'Il y a un relachement quant aux résultats mrs les éducateurs', NULL);
INSERT INTO `clubs_infos` VALUES (210, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (264, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (268, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (280, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (292, 1, '', 'Reprise des entraînements mardi 6 août à Loisin pour le groupe U19.', NULL);
INSERT INTO `clubs_infos` VALUES (304, 1, '', 'Réunion technique le 04 Mars 2013 à 20 heure, au service des sport .', NULL);
INSERT INTO `clubs_infos` VALUES (309, 1, '', 'TOURNOI FEMININ 1er SEPTEMBRE A SAVENAY. SENIORS U 18 a pas d\'âge.... VENEZ TRES NOMBREUX', NULL);
INSERT INTO `clubs_infos` VALUES (316, 1, '', 'Mise en place du projet de gestion Joueurs / Educateurs et Compétitions / Entrainements avec le site internet MyCoach', NULL);
INSERT INTO `clubs_infos` VALUES (318, 1, '', ' ', NULL);
INSERT INTO `clubs_infos` VALUES (320, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (322, 1, '', 'RDV à 17H45 à MARCQ pour le stage INITIATEUR 1', NULL);
INSERT INTO `clubs_infos` VALUES (338, 1, '', 'Le Cergy Pontoise Football Club te souhaite la bienvenue dans son espace MyCoach version 2015-2016. Cet accès doit être la référence de base de données de notre club.    Prochaine Commission Technique Ecole de Foot le DIMANCHE 27 SEPTEMBRE à 18H30. Présence de tous obligatoire', NULL);
INSERT INTO `clubs_infos` VALUES (339, 1, '', 'BIENVENUE AUX COACHS SUR MY COACH. GUY\r\nMERCI FRED ET LE BUREAU', NULL);
INSERT INTO `clubs_infos` VALUES (340, 1, '', 'UN CLUB UNE FAMILLE', NULL);
INSERT INTO `clubs_infos` VALUES (349, 1, '', 'Coupe nationale U15 du 17 au 21 avril 2012 au CTNFS pour l\'équipe de la LPIFF', NULL);
INSERT INTO `clubs_infos` VALUES (354, 1, '', 'REUNION EDUCATEURS DE LA SAINT PAULOISE FC le Jeudi 12 Avril 2012 au club house. ', NULL);
INSERT INTO `clubs_infos` VALUES (360, 1, '', 'rdv demain', NULL);
INSERT INTO `clubs_infos` VALUES (367, 1, '', 'bjr, merci de pas oublier la reunion prevu vendredi à 15h ', NULL);
INSERT INTO `clubs_infos` VALUES (384, 1, '', 'PROCHAINE REUNION LE LUNDI 31 aout 2015 18H00 CLUB HOUSE.........', NULL);
INSERT INTO `clubs_infos` VALUES (387, 1, '', 'Prochain CA du HAC le Lundi 17 Décembre 2012 au Foyer de Baquet à 19H.', NULL);
INSERT INTO `clubs_infos` VALUES (402, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (407, 1, '', 'Finale challenge Arvis samedi à 19 h aux aix', NULL);
INSERT INTO `clubs_infos` VALUES (411, 1, '', 'Merci aux Educateurs de mettre à jour leur profil Mycoach!! La formation aura lieu tès prochainement..je vous tiens au courant. Et n\'oubliez pas, ce logiciel est un investissement pour le club, alors utilisez le correctement! Merci!', NULL);
INSERT INTO `clubs_infos` VALUES (414, 1, '', 'AG DU 21/06/2012  A PARTIR DE 20H', NULL);
INSERT INTO `clubs_infos` VALUES (415, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (421, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (422, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (439, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (447, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (451, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (458, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (461, 1, '', 'Pensez à créer les différents comptes équipes (ONGLET EQUIPES) de vos Collègues: Laurent GANGNEUX, Yohann HONORE, Frédéric HONORÉ, ...', NULL);
INSERT INTO `clubs_infos` VALUES (462, 1, '', 'Pensez à créer les comptes de vos collègues, dans la rubrique EQUIPES (renseigner leurs mails) : Nicolas Maillet, Robert CADET, Jean-Yves Blandin, Michel CADOR, ...', NULL);
INSERT INTO `clubs_infos` VALUES (463, 1, '', 'Pensez à créer les comptes de vos collègues depuis l\'onglet EQUIPES (en renseignant leurs mails)', NULL);
INSERT INTO `clubs_infos` VALUES (464, 1, '', 'Pensez à créer les comptes de vos collègues, en vous rendant dans l\'onglet EQUIPES. Bonne navigation sur My Coach Foot.', NULL);
INSERT INTO `clubs_infos` VALUES (469, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (470, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (471, 1, '', 'Réunion technique', NULL);
INSERT INTO `clubs_infos` VALUES (484, 1, '', '« Celui qui renonce à devenir meilleur cesse déjà d’être bon. »\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (490, 1, '', 'Bonjour et bienvenu à tous sur ce nouvel outil de gestion...', NULL);
INSERT INTO `clubs_infos` VALUES (491, 1, '', 'BIENVENUE REUNION TECHNIQUE LE 20 JUIN 2012', NULL);
INSERT INTO `clubs_infos` VALUES (514, 1, '', 'FCR remiremont', NULL);
INSERT INTO `clubs_infos` VALUES (519, 1, '', 'ghujikolmyhujikui', NULL);
INSERT INTO `clubs_infos` VALUES (522, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (523, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (543, 1, '', 'Bienvenu au stade de Vallauris', NULL);
INSERT INTO `clubs_infos` VALUES (554, 1, '', ' ', NULL);
INSERT INTO `clubs_infos` VALUES (562, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (577, 1, '', 'Test', NULL);
INSERT INTO `clubs_infos` VALUES (578, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (586, 1, '', ' Urgent report de la réunion  des éducateurs au mercredi 12 décembre  a 19h.', NULL);
INSERT INTO `clubs_infos` VALUES (592, 1, '', 'dambach', NULL);
INSERT INTO `clubs_infos` VALUES (614, 1, '', '   ', NULL);
INSERT INTO `clubs_infos` VALUES (617, 1, '', 'rentree de foot\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (675, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (679, 1, '', 'reunion rentre du foot', NULL);
INSERT INTO `clubs_infos` VALUES (687, 1, '', 'reunion', NULL);
INSERT INTO `clubs_infos` VALUES (704, 1, NULL, 'Changement de fil info !', NULL);
INSERT INTO `clubs_infos` VALUES (713, 1, '', 'Avant le 15 août, MY COACH sera opérationnel pour chaque éducateur...Si problèmes, me contacter. Eric BOURGET', NULL);
INSERT INTO `clubs_infos` VALUES (719, 1, '', 'Les bilans de la semaine dernière????', NULL);
INSERT INTO `clubs_infos` VALUES (725, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (735, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (747, 1, '', 'Messieurs les coaches, pensez à remplir les bulletin afin de mettre en place les entretiens la semaine prochaine. Merci.', NULL);
INSERT INTO `clubs_infos` VALUES (748, 1, '', 'Passage à la saison 2013-14 effectué', NULL);
INSERT INTO `clubs_infos` VALUES (749, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (762, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (765, 1, '', 'Bienvenue dans MyCoach', NULL);
INSERT INTO `clubs_infos` VALUES (812, 1, '', 'Bonjour à tous....Le Président Yoackim BALICCO \r\nEt le comité directeur de l’U.S. Pégomas\r\nVous présentent leurs félicitations pour vos résultats, et les différentes montées en catégories supérieures.\r\nRendez-vous pour la saison 2013/2014 avec de bon résultats à venir, merci à tous.....allez Pégomas!!!', NULL);
INSERT INTO `clubs_infos` VALUES (819, 1, '', 'Réunion formation My Coach pour football à 11 le lundi 16 Novembre à 19h 30 au Stade Louis II', NULL);
INSERT INTO `clubs_infos` VALUES (862, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (894, 1, '', 'Pensez à mettre à jour vos fiches joueurs et contacter mycoach si besoin !', NULL);
INSERT INTO `clubs_infos` VALUES (899, 1, NULL, 'INFO SECTION JEUNES :\r\n\r\nVendredi 14 Novembre, dernier délai pour déposer les séances d\'entrainement de la semaine prochaine. Bruno', NULL);
INSERT INTO `clubs_infos` VALUES (936, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (955, 1, '', 'L\'USN SPAY est sur my Coach', NULL);
INSERT INTO `clubs_infos` VALUES (988, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (1001, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (1002, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (1006, 1, '', 'On rentre dans une période difficile, soyez courageux, maintenez les efforts !', NULL);
INSERT INTO `clubs_infos` VALUES (1030, 1, '', 'Bons matchs ce week-end!! ', NULL);
INSERT INTO `clubs_infos` VALUES (1042, 1, '', 'Tirage Coupe du Centre Seniors le 14 Février 2016 \r\nUSM Montargis (DH) ou US Orléans Loiret F. (2) (DH) / Blois Foot 41 (DH)\r\n\r\nTirage Coupe du Centre U19 le 16 Janvier à 15H\r\nBlois Foot 41 (DH) / USM Saran (DH)\r\n\r\nWeekend du 09 Janvier 2016\r\nSeniors DH\r\nRencontre amicale Samedi à 16H Stade des Allées Honneur\r\nBF41 / Berri. Châteauroux (CFA2)\r\n\r\nSeniors DHR\r\nRencontre amicale Vendredi à 19H30 à Montlouis\r\nMontlouis / BF41\r\n\r\nU19DH\r\nRencontre amicale Samedi à 10H30 Stade Honoré de Balzac\r\nBF41 / Vineuil Sp\r\n\r\nU18 Coupe Loir et Cher à Saint Aignan 18H\r\nSt Aignan / BF41\r\n\r\nU16 DH Rencontre amicale Samedi à 17H à Tours\r\nTours Fc / BF41\r\n\r\nU15 DH Rencontre amicale Samedi à 17H30  Stade Honore de Balzac\r\nBF41 / Chitenay\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n ', NULL);
INSERT INTO `clubs_infos` VALUES (1052, 1, '', 'PROCHAINE RÉUNION TECHNIQUE LE LUNDI 01 JUILLET à 20H00 - AU SIEGE DU CLUB 191 CHEMIN DESCHANETS\r\n\r\n\r\nOrdre du jour:\r\n   \r\n   - projection sur le thème de la programmation annuel \r\n   - remarque du responsable technique, lors de ses passages aux séances d\'entraînements jeunes\r\n   - questions divers', NULL);
INSERT INTO `clubs_infos` VALUES (1080, 1, '', 'Rappel: plateau débutant du 1novembre. Présence indispensable des éducateurs', NULL);
INSERT INTO `clubs_infos` VALUES (1082, 1, '', 'xxxxwxx', NULL);
INSERT INTO `clubs_infos` VALUES (1150, 1, '', '_/ Soufiane 06.18.98.19.57 \\\\__/n\\\'hésitez pas à me contacter \\\\_', NULL);
INSERT INTO `clubs_infos` VALUES (1164, 1, '', 'Tournoi u13 les 5 et 6 septembre a Gignac ', NULL);
INSERT INTO `clubs_infos` VALUES (1234, 1, '', 'Ramener photocopie des diplômes', NULL);
INSERT INTO `clubs_infos` VALUES (1251, 1, '', 'Bonjour, Plusieurs effectif n\'ont toujours pas été intégrés, merci de vous diriger vers moi pour régularisation. Saad', NULL);
INSERT INTO `clubs_infos` VALUES (1269, 1, '', 'JOURNEE  MANU ET ADRIANO  DIMANCHE 23 JUIN. VENEZ NOMBREUX', NULL);
INSERT INTO `clubs_infos` VALUES (1273, 1, '', 'Premier match de Coupe de France pour les Seniors 1 le Dimanche 30 Aout contre la PHa du CDJ Antibes\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (1316, 1, '', 'La vraie réussite d\'une équipe, c\'est d\'assurer la compétitivité dans la pérennité ', NULL);
INSERT INTO `clubs_infos` VALUES (1334, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (1359, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (1367, 1, '', 'prochaine journée pédagogique : lundi 14 octobre // détections -1er tour : dimanche 6 octobre// Gen Adidas Cup : 11-14 octobre @MTL // détection 2eme tour : samedi 19 octobre 9-12h30', NULL);
INSERT INTO `clubs_infos` VALUES (1437, 1, '', 'ATTENTION : VENDREDI 1 NOVEMBRE 2013, SUPER LOTO DE L\'OLYMPIQUE ROVENAIN A 16H A LA SALLE JENNIFER AU ROVE !!!', NULL);
INSERT INTO `clubs_infos` VALUES (1517, 1, '', 'Joueurs suspendus pour ce weekend : Fred et franck', NULL);
INSERT INTO `clubs_infos` VALUES (1533, 1, '', 'CA du HAC Lundi 14/10/2013 à BAQUET à 19H30.//\r\nA essayer : le site : yaentrainement.fr //\r\nPour toute question concernant l\'utilisation de MyCoach, appelez  le 04.93.79.93.70 (9h-20h).//', NULL);
INSERT INTO `clubs_infos` VALUES (1597, 1, '', 'Bonne semaine à tous\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (1602, 1, '', 'Séance du mardi 08/10/2013 (Repas 13h15 - Invitation Malik).\r\nMatch PEFA Avenir - Sélection CDA U15 Mercredi 09/10 à 15h (RDV 13h45 - Herbe Briffaut).', NULL);
INSERT INTO `clubs_infos` VALUES (1621, 1, '', 'Réunion le 3 octobre à 15 heures à la salle Valère Lamie', NULL);
INSERT INTO `clubs_infos` VALUES (1643, 1, '', 'Prochaine réunion éducateurs le lundi 13 Avril à 19h30 à la buvette de st Cézaire. Merci de vous organiser en conséquence.', NULL);
INSERT INTO `clubs_infos` VALUES (1715, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (1875, 1, NULL, 'Hello votre nouvelle saison est prête à démarrer ! Votre activation a été faite ! A disposition pour plus d\'infos !', NULL);
INSERT INTO `clubs_infos` VALUES (1916, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (1924, 1, NULL, '\r\n\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (1955, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (1993, 1, NULL, 'Bonjour à tous, \r\nComme dit lors, de la réunion : -commencez a remplir les fiches individuelles.\r\n- Concernant les infos des matchs, il y a des information qui s\\\'avèrent être des détails, mais qui sont importantes sur le suivi des joueurs du club comme pour le suivi des joueurs susceptibles d\\\'être recruter, alors je ne demande pas de remplir jour après jours mais essayez svp d\\\'être régulier pour ne pas être débordés et d\\\'omettre certaines infos\r\n\r\nMerci d\\\'avance.', NULL);
INSERT INTO `clubs_infos` VALUES (2000, 1, NULL, 'Réunion éducateurs le 31/12/2015 matin RDV 8h30 au club house. Préparer les prochaines planifications', NULL);
INSERT INTO `clubs_infos` VALUES (2002, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2018, 1, NULL, 'Tournoi en salle U12 le 24/2 et U13 le 25/2.', NULL);
INSERT INTO `clubs_infos` VALUES (2031, 1, NULL, '\r\n\r\n\r\n\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2043, 1, NULL, 'JOYEUSES FETES DE FIN D\'ANNEE 2015 ET REPRISE MARDI 5 JANVIER 2016 20H00 STADE BRAINS', NULL);
INSERT INTO `clubs_infos` VALUES (2071, 1, '', '', NULL);
INSERT INTO `clubs_infos` VALUES (2074, 1, NULL, 'Bonjour à tous les éducateurs,\r\nIl est important de bien mettre à jour toutes vos fiches de match et d\'entrainement pour préparer les bilans de fin de saison, quelques groupes ont beaucoup de retard or pour établir le suivi des fiches de joueurs d\'une saison sur l\'autre il est indispensable que tout soit correctement renseigné. MERCI DE REACTUALISER\r\n\r\nNous allons bientôt reprendre la seconde semaine des tests de nos joueurs.\r\nVoici le programme tel qu\'il a du vous être communiqué \r\nMardi 7 AVRIL    U12\r\nJEUDI 9 Avril  U14 et U15\r\nLUNDI 13 AVRIL   U13\r\nMERCREDI  15 AVRIL   U16 et U17    U19\r\n\r\nUn ou deux responsables sera (ont) présent(s) pour vous aider.\r\nMerci de prévoir la fiche de saisie des résultats.\r\n\r\nPour toutes questions, tu vois avec ton responsable de pôle.\r\n\r\nPour des renseignements complémentaires, tu peux contacter CHRISTIAN PORNIN  06 16 98 14 10    ch.pornin@noos.fr\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2076, 1, NULL, 'MARDI 8 SEPTEMBRE 18H REUNION EDUCATEURS', NULL);
INSERT INTO `clubs_infos` VALUES (2132, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2136, 1, NULL, 'La reprise de l\\\'entraînement est programmée le vendredi 01 août 2014. ', NULL);
INSERT INTO `clubs_infos` VALUES (2141, 1, NULL, 'Merci de bien renseigner les présences aux entraînements afin que nous puissions faire un 1er point au 15 août', NULL);
INSERT INTO `clubs_infos` VALUES (2145, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2149, 1, NULL, 'Tournoi en salle u 11 le 11/11/2014', NULL);
INSERT INTO `clubs_infos` VALUES (2177, 1, NULL, 'salut a tous \r\nbravo pour vos résultat \r\ndemander ou redemander a vos joueurs pour qu\\\'il n’y est pas de soucis par rapport a leur licence \r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2210, 1, NULL, 'Prochaine réunion technique le samedi 07 novembre 2015 de 9h à 12h30...\r\n\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2214, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2218, 1, NULL, 'je vous adresse tous mes voeux pour 2015 .  eric', NULL);
INSERT INTO `clubs_infos` VALUES (2246, 1, NULL, 'Bonne année à tous.... N\'oubliez pas de renseigner le site My Coach pour les séances et les comptes rendus matchs...', NULL);
INSERT INTO `clubs_infos` VALUES (2249, 1, NULL, 'Specifique gardien : u15 mercredi 15h u17 mercredi 16h u13 mardi 16h30\r\nThème pour octobre : tactique : principes de progression ( aide au porteur appui soutien appel) technique: prise de balle et passe\r\nphysique : maitrise des appuis et coordination\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2261, 1, NULL, ' ', NULL);
INSERT INTO `clubs_infos` VALUES (2295, 1, NULL, 'REUNION EDUCATEURS lundi 9 novembre 2015 de 19h00 à 20h30 au club house de MAS GRENIER', NULL);
INSERT INTO `clubs_infos` VALUES (2313, 1, NULL, 'Bonjour', NULL);
INSERT INTO `clubs_infos` VALUES (2323, 1, NULL, 'Réunion Vendredi 31 octobre à 19h au stade ', NULL);
INSERT INTO `clubs_infos` VALUES (2340, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2345, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2346, 1, NULL, '\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2361, 1, NULL, 'Sébastien Dulac: mycoach 06 18 61 69 57', NULL);
INSERT INTO `clubs_infos` VALUES (2362, 1, NULL, 'Bonjour,\r\nPAS DE PANIQUE, je suis entrain de changer les paramètres afin que vous puissiez accéder avec les données de la 2015/2016', NULL);
INSERT INTO `clubs_infos` VALUES (2367, 1, NULL, 'Pour tout renseignement sur My Coach Foot, contacter Sébastien DULAC 06 18 61 69 57. Réunion My Coach RDV ce soir à 16h45', NULL);
INSERT INTO `clubs_infos` VALUES (2368, 1, NULL, 'entrainement vendredi a 18H30 ', NULL);
INSERT INTO `clubs_infos` VALUES (2369, 1, NULL, 'Pour tout renseignement concernant My Coach Foot, contacter Sébastien DULAC au 06 18 61 69 57.\r\n', NULL);
INSERT INTO `clubs_infos` VALUES (2374, 1, NULL, 'NOUVELLE SAISON MERCI DE METTRE A JOUR VOS INFORMATIONS ET DE VOUS RAPPROCHEZ DE MOI POUR PAUFINER LES DETAILS. BONNE VACANCES !\r\n\r\n\r\n\r\n ', NULL);
INSERT INTO `clubs_infos` VALUES (2386, 1, NULL, 'Pour toute information concernant My Coach Foot, vous pouvez me contacter au 06 18 61 69 57 (Sébastien DULAC)', NULL);
INSERT INTO `clubs_infos` VALUES (2387, 1, NULL, 'Pour tout renseignement sur My Coach Foot, contacter Sébastien DULAC: 06 18 61 69 57', NULL);
INSERT INTO `clubs_infos` VALUES (2430, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2458, 1, NULL, 'Rencontre \"Parents-Educateurs\" Catégories U6/U7 et U8/U9 prévue le mercredi à 08 avril 2015 à 16h00 au Stade de RIVES (Salle)', NULL);
INSERT INTO `clubs_infos` VALUES (2475, 1, NULL, 'Programme du week end : Séniors A contre à Plomelin / Séniors B :  repos / Séniors C contre Plozevet 2 / Séniors D : repos / Séniors E : repos.', NULL);
INSERT INTO `clubs_infos` VALUES (2480, 1, NULL, 'Séance d\'entrainement : Echauffement collectif : 10 \' / Jeu problème ou ludique : 20 \' / Situation de résolution de problème : 20 \' / Exercice ou travail athlétique : 20 \' / Jeu problème : 10 \' / Jeu global de fin de séance : 10\'.', NULL);
INSERT INTO `clubs_infos` VALUES (2491, 1, NULL, 'reunion', NULL);
INSERT INTO `clubs_infos` VALUES (2523, 1, NULL, 'Réunion de tous les sélectionneurs le mardi 02 novembre à 10H, thème évoqué : visionnage des futures adversaires, prochain rassemblement, organisation des sélections.', NULL);
INSERT INTO `clubs_infos` VALUES (2527, 1, NULL, '', NULL);
INSERT INTO `clubs_infos` VALUES (2534, 1, NULL, 'Reunions a venir:         \r\n*** Reunion Technique #4 (FE, FC, FS): Samedi 06/02/2016, Centre, 9:30-11:30 (presence de tous tres fortement recommendee) ***', NULL);
INSERT INTO `clubs_infos` VALUES (2542, 1, NULL, 'Penser à distribuer les licences à vos joueuses', NULL);
INSERT INTO `clubs_infos` VALUES (2547, 1, NULL, 'ATTENTION : Foot à 11, COUPE DU RHONE LE MERCREDI 11 NOV. ', NULL);
INSERT INTO `clubs_infos` VALUES (2549, 1, NULL, 'Felicitations a toutes les categories pour leurs victoire de ce week end. guillaume', NULL);
INSERT INTO `clubs_infos` VALUES (2557, 1, NULL, 'Bonne Année 2016 pour toutes les équipes du FCC!', NULL);
INSERT INTO `clubs_infos` VALUES (2568, 1, NULL, 'EN ROUGE ET NOIR, ENSEMBLE VERS LA VICTOIRE !', NULL);
INSERT INTO `clubs_infos` VALUES (2573, 1, NULL, 'Attendez avant de rentrer des joueurs, nous allons réaliser l\'importation', NULL);
INSERT INTO `clubs_infos` VALUES (2604, 1, NULL, 'Bonne reprise de la compétition \"L\'or du Chéran coule dans nos veines\" ', NULL);
INSERT INTO `clubs_infos` VALUES (2624, 1, NULL, 'Pour toute question relative à la plateforme, contacter Sébastien Dulac au 0618616957', NULL);
INSERT INTO `clubs_infos` VALUES (2626, 1, NULL, 'Réunion technique U15/U17/U19 : LUNDI 21/12 à 18h30 au foyer', NULL);
INSERT INTO `clubs_infos` VALUES (2628, 1, NULL, 'PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA PHA', NULL);
INSERT INTO `clubs_infos` VALUES (2693, 1, NULL, 'Pensez à faire vos bilans de catégorie en vue de la réunion du 19 Décembre.', NULL);
INSERT INTO `clubs_infos` VALUES (2806, 1, NULL, 'Réunion technique lundi 10 aout à 18h', NULL);
INSERT INTO `clubs_infos` VALUES (2939, 1, NULL, 'Réunion technique le samedi 26 septembre à 10h00 bureau de la rhodia', NULL);
INSERT INTO `clubs_infos` VALUES (2953, 1, NULL, 'Offre : - 20% pour tout nos abonnés sur toutes les réservations de 14h à 18h jusqu\'au 31 octobre 2015', NULL);
